import { Component } from '@angular/core'
import { Title, Meta } from '@angular/platform-browser'

@Component({
  selector: 'app-home',
  templateUrl: 'home.component.html',
  styleUrls: ['home.component.css'],
})
export class Home {
  rawacea: string = ' '
  raw5lyd: string = ' '
  raws1yq: string = ' '
  raw4l9l: string = ' '
  raw7tj1: string = ' '
  rawwiih: string = ' '
  rawyg2k: string = ' '
  rawzv8z: string = ' '
  rawee53: string = ' '
  rawlpv1: string = ' '
  rawwh1z: string = ' '
  rawmdjk: string = ' '
  rawyiqv: string = ' '
  rawz56r: string = ' '
  rawcpb9: string = ' '
  rawondy: string = ' '
  raw2kjf: string = ' '
  rawli4i: string = ' '
  rawqr7c: string = ' '
  rawxyx5: string = ' '
  rawjcad: string = ' '
  rawfuwa: string = ' '
  raw9vlq: string = ' '
  raw5wu5: string = ' '
  rawa5i8: string = ' '
  raw35ru: string = ' '
  rawfh09: string = ' '
  rawhnc8: string = ' '
  rawcvkr: string = ' '
  raw7ms8: string = ' '
  rawtfzy: string = ' '
  rawktke: string = ' '
  rawaviw: string = ' '
  raw8x6c: string = ' '
  rawro1k: string = ' '
  rawmuis: string = ' '
  rawixz2: string = ' '
  rawmy88: string = ' '
  raw8rys: string = ' '
  raw9ede: string = ' '
  raw0asb: string = ' '
  raw6uk7: string = ' '
  rawnat6: string = ' '
  raw40kw: string = ' '
  rawfd2v: string = ' '
  raw73xg: string = ' '
  rawldgq: string = ' '
  rawo176: string = ' '
  raw015k: string = ' '
  rawb9l2: string = ' '
  raw3fku: string = ' '
  raw7sr6: string = ' '
  raw4qag: string = ' '
  rawz474: string = ' '
  rawd266: string = ' '
  raw75pb: string = ' '
  raw4alk: string = ' '
  rawjwt5: string = ' '
  rawxejt: string = ' '
  raww7m8: string = ' '
  rawthkg: string = ' '
  rawdxb1: string = ' '
  rawumkq: string = ' '
  rawv17j: string = ' '
  rawls19: string = ' '
  rawzgt6: string = ' '
  raw3jr7: string = ' '
  raw1kz1: string = ' '
  raw45vr: string = ' '
  rawstyi: string = ' '
  rawf56n: string = ' '
  raw6t25: string = ' '
  raw98aw: string = ' '
  raw1vus: string = ' '
  rawfgg5: string = ' '
  raw7gmf: string = ' '
  raw315e: string = ' '
  rawnj1n: string = ' '
  raw6a5a: string = ' '
  raw6x7u: string = ' '
  rawqpow: string = ' '
  rawytkq: string = ' '
  constructor(private title: Title, private meta: Meta) {
    this.title.setTitle('Tilapia con Biofloc')
    this.meta.addTags([
      {
        property: 'og:title',
        content: 'Tilapia con Biofloc',
      },
    ])
  }
}
